{ lib, ... }: {
  _module.args.mkModuleOption = args @ { key, static ? { }, ... }:
    lib.mkOption {
      type = lib.types.deferredModuleWith { staticModules = [ static ]; };
      apply = module: { inherit key; imports = [ module ]; };
      default = { };
    };

  # Package names (as lib.getName reports them) permitted despite an
  # unfree license. The single source for the
  # nixpkgs.config.allowUnfreePredicate set by modules/nixos/base.nix and
  # by the standalone home-manager exports in modules/home.nix. Verified
  # against meta.license at the locked revisions: everything else in the
  # fleet (ghostty, kodi, psysonic, rigup) is free-licensed. Names are
  # per-derivation (lib.getName), so wrapped packages list their
  # unwrapped halves too.
  _module.args.unfreeNames = [
    "discord"
    "discord-unwrapped"
    "obsidian"
    "1password"
    "1password-cli"
  ];

  # The personal cachix binary cache (nix-configs): the substituter URL
  # and the public half of our self-owned signing keypair (the secret
  # half is the agenix secret secrets/cachix-signing-key.age; the pair
  # was generated by `cachix generate-keypair nix-configs`, which also
  # registered the public half at cachix). Single source for
  # modules/nixos/base.nix (the desktop's nix.settings) and
  # modules/batman/cachix.nix (the Mac's standalone nix.conf).
  _module.args.cachixCache = {
    url = "https://nix-configs.cachix.org";
    publicKey = "nix-configs.cachix.org-1:7Ujoj71uBp3xoxOBwPF8CTJAmoaz0+I/Dm1yK0dNyBw=";
  };
}
