# The desktop's hardware facts. Originally generated by
# nixos-generate-config; now maintained by hand alongside the
# declarative partition layout in ./_disko.nix. Mounts reference
# partitions by PARTLABEL — the labels _disko.nix sets on fresh
# installs, and that were set once in place on the original
# hand-partitioned disk (sgdisk --change-name; see docs/bootstrap.md,
# "Adopting the existing disk") — so both disks satisfy this exact
# config.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "coretemp" "k10temp" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-partlabel/nixos-root";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/nixos-ESP";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
