# The desktop's hardware facts. Originally generated by
# nixos-generate-config; now maintained by hand alongside the
# declarative partition layout in ./_disko.nix. Mounts reference
# partitions by PARTLABEL — the labels _disko.nix sets on fresh
# installs, and that were set once in place on the original
# hand-partitioned disk (sgdisk --change-name; see docs/bootstrap.md,
# "Adopting the existing disk") — so both disks satisfy this exact
# config.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "coretemp" "k10temp" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-partlabel/nixos-root";
    fsType = "btrfs";
  };

  # The `nix` and `home` subvolumes with their own mounts — the fleet
  # canonical layout, identical to framework/_hardware.nix (unified
  # 2026-09-06 after the unmounted-nested-subvol difference tripped
  # snapper's ensure guard). Both subvolumes already existed on this
  # disk (hand-created at the original install, subvolid 256/257 —
  # the same ids the laptop's installer made), reachable through the
  # top-level mount; these entries only give each a mount of its
  # own. No data moves — the mount layers over the same subvolume
  # the toplevel was already exposing at that path.
  fileSystems."/nix" = {
    device = "/dev/disk/by-partlabel/nixos-root";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-partlabel/nixos-root";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/nixos-ESP";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
