# The desktop's hardware facts. Originally generated by
# nixos-generate-config; now maintained by hand alongside the
# declarative partition layout in ./_disko.nix. Since the LUKS
# rework there is a two-layer device story (full narrative in
# framework/_hardware.nix): the PARTITION is identified by PARTLABEL
# (nixos-ESP, nixos-root), and the btrfs lives at
# /dev/mapper/cryptroot — the unlocked LUKS2 container the root
# partition holds. The live unencrypted disk predates the rework;
# converting it in place is the runbook in docs/bootstrap.md.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "tpm_crb" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "coretemp" "k10temp" ];
  boot.extraModulePackages = [ ];

  # The root LUKS2 container (partition = nixos-root, formatted by
  # _disko.nix) — same unlock policy as framework/_hardware.nix:
  # tpm2-device=auto unseals unattended (this box reboots headless
  # via WoL; its TPM was confirmed 2026-09-06, /dev/tpmrm0 — Intel
  # PTT, CRB interface, hence the tpm_crb initrd module above), with
  # the passphrase + recovery slots kept as typed fallbacks for a
  # firmware update that shifts PCR7. crypttabExtraOpts — NOT
  # crypttabExtraOptions — is the crypttab(5) spelling; allowDiscards
  # keeps services.fstrim working through the mapping.
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-partlabel/nixos-root";
    allowDiscards = true;
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };

  # Fleet btrfs mount options — compress=zstd:3 + noatime, the full
  # why in framework/_hardware.nix — stated per mount because btrfs
  # mount options do not inherit from / to subvolume mounts. Same
  # list as _disko.nix's fresh-install layout (contract: metal laid
  # down by disko and the live mount table agree).
  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "compress=zstd:3" "noatime" ];
  };

  # The `nix` and `home` subvolumes with their own mounts — the fleet
  # canonical layout, identical to framework/_hardware.nix (unified
  # 2026-09-06 after the unmounted-nested-subvol difference tripped
  # snapper's ensure guard). Both subvolumes already existed on this
  # disk (hand-created at the original install, subvolid 256/257 —
  # the same ids the laptop's installer made), reachable through the
  # top-level mount; these entries only give each a mount of its
  # own. No data moves — the mount layers over the same subvolume
  # the toplevel was already exposing at that path.
  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress=zstd:3" "noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=home" "compress=zstd:3" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/nixos-ESP";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
