# The framework laptop's hardware facts. Originally generated by
# nixos-generate-config after the flash-drive install (2026-09-05);
# now maintained by hand alongside the declarative partition layout in
# ./_disko.nix. Mounts reference partitions by PARTLABEL — the labels
# _disko.nix sets on fresh installs, and that were renamed once in
# place on the installer-disk (sgdisk --change-name 2026-09-06; see
# docs/bootstrap.md, "Adopting the existing disk") — so both disks
# satisfy this exact config. The btrfs partition mounts three ways:
# its top-level (subvolid 5) at /, plus the `home` and `nix`
# subvolumes.
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-partlabel/framework-root";
    fsType = "btrfs";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-partlabel/framework-root";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-partlabel/framework-root";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/framework-ESP";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partlabel/framework-swap";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
