# The framework laptop's hardware facts. Originally generated by
# nixos-generate-config after the flash-drive install (2026-09-05);
# now maintained by hand alongside the declarative partition layout in
# ./_disko.nix. Since the LUKS rework there is a two-layer device
# story: the PARTITION is identified by its PARTLABEL (framework-ESP,
# framework-root — what _disko.nix sets on fresh installs), and the
# btrfs lives at /dev/mapper/cryptroot, the unlocked LUKS2 container
# the framework-root partition holds. The 2026-09-06 unencrypted live
# disk no longer satisfies this file — migrating it means the disko
# wipe + borg restore runbook in _disko.nix's header.
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    # AMD fTPM speaks the CRB interface; stage-1 systemd-cryptsetup
    # needs /dev/tpmrm0 to read the TPM-sealed keyslot below. The
    # nixpkgs LUKS machinery already pulls the tpm drivers into the
    # initrd when a luks device is declared — this explicit entry only
    # pins the dependency so the unlock policy below stays
    # self-documenting (the repo pins nixpkgs defaults elsewhere for
    # the same reason, e.g. sshd's PermitRootLogin in system/base.nix).
    "tpm_crb"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # The root LUKS2 container (partition = framework-root, formatted
  # by _disko.nix). Unlock policy — the reason LUKS costs zero extra
  # prompts:
  #   - tpm2-device=auto: the TPM2-sealed keyslot (enrolled on the box
  #     per _disko.nix's runbook) unlocks unattended — plymouth
  #     straight into SDDM, exactly the pre-LUKS boot UX. Sealed to
  #     PCR7 only (the systemd-cryptenroll default): generation/kernel
  #     churn never shifts it; a firmware update flipping Secure Boot
  #     state does — which is what the fallback slots are for.
  #   - fallbacks, deliberately kept (never --wipe-slot them): the
  #     original passphrase slot plus the enrolled recovery key, typed
  #     at the console only when the TPM refuses.
  # crypttabExtraOpts — NOT crypttabExtraOptions — is the crypttab(5)
  # options spelling (luksroot.nix); allowDiscards keeps
  # services.fstrim working through the mapping. On this nixpkgs there
  # is only the systemd stage 1 anyway (scripted initrd removed in
  # 26.11), which is what speaks tpm2-device at all.
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-partlabel/framework-root";
    allowDiscards = true;
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };

  # The btrfs inside the container mounts three ways: its top-level
  # (subvolid 5) at /, plus the `home` and `nix` subvolumes.
  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/framework-ESP";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # No swap partition since the LUKS rework (the 67G installer
  # artifact is gone — _disko.nix's header covers why zramSwap +
  # earlyoom + s2idle make it dead weight, and why plaintext swap
  # would have undone the encryption).
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
