# The framework laptop's hardware facts. Originally generated by
# nixos-generate-config after the flash-drive install (2026-09-05);
# now maintained by hand alongside the declarative partition layout in
# ./_disko.nix. Since the LUKS rework there is a two-layer device
# story: the PARTITION is identified by its PARTLABEL (framework-ESP,
# framework-root — what _disko.nix sets on fresh installs), and the
# btrfs lives at /dev/mapper/cryptroot, the unlocked LUKS2 container
# the framework-root partition holds. The 2026-09-06 unencrypted live
# disk no longer satisfies this file — migrating it means the disko
# wipe + borg restore runbook in _disko.nix's header.
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    # AMD fTPM speaks the CRB interface; stage-1 systemd-cryptsetup
    # needs /dev/tpmrm0 to read the TPM-sealed keyslot below. The
    # nixpkgs LUKS machinery already pulls the tpm drivers into the
    # initrd when a luks device is declared — this explicit entry only
    # pins the dependency so the unlock policy below stays
    # self-documenting (the repo pins nixpkgs defaults elsewhere for
    # the same reason, e.g. sshd's PermitRootLogin in system/base.nix).
    "tpm_crb"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # The root LUKS2 container (partition = framework-root, formatted
  # by _disko.nix). Unlock policy — the reason LUKS costs zero extra
  # prompts:
  #   - tpm2-device=auto: the TPM2-sealed keyslot (enrolled on the box
  #     per _disko.nix's runbook) unlocks unattended — plymouth
  #     straight into SDDM, exactly the pre-LUKS boot UX. Sealed to
  #     PCR7 only (the systemd-cryptenroll default): generation/kernel
  #     churn never shifts it; a firmware update flipping Secure Boot
  #     state does — which is what the fallback slots are for.
  #     (Caveat observed 2026-09-07, during Secure Boot enrollment: this
  #     firmware does NOT extend SB-policy changes into the SHA256
  #     PCR7 bank — the whole PK swap + SB-enforce transition booted
  #     promptless, the 2026-09-06 seal still matching. See
  #     _secure-boot.nix's runbook step 7 for what that means.)
  #   - fallbacks, deliberately kept (never --wipe-slot them): the
  #     original passphrase slot plus the enrolled recovery key, typed
  #     at the console only when the TPM refuses.
  #   - fido2-device=auto: a YubiKey touch tier between the TPM and
  #     the typed passphrase. systemd-cryptsetup tries unlock methods
  #     in the order keyfile → tpm2 → fido2 → pkcs11 → passphrase, so
  #     the daily boot still unlocks zero-touch via the TPM; the key
  #     only matters when the TPM refuses (the SB-policy/firmware-
  #     update case above) — plug it in, touch it when it blinks, no
  #     passphrase typing. Touch-only by design: cryptenroll's fido2
  #     defaults ask for user presence, not a PIN (possession factor;
  #     the passphrase remains the knowledge factor). USB plug
  #     required — NFC does not work at boot. Key absent? cryptsetup
  #     shows an insert-token prompt for token-timeout= (30s default),
  #     then falls through to the passphrase — same UX as before the
  #     key existed.
  # crypttabExtraOpts — NOT crypttabExtraOptions — is the crypttab(5)
  # options spelling (luksroot.nix); allowDiscards keeps
  # services.fstrim working through the mapping. On this nixpkgs there
  # is only the systemd stage 1 anyway (scripted initrd removed in
  # 26.11), which is what speaks tpm2-device/fido2-device at all
  # (luksroot.nix asserts exactly this pairing — the legacy
  # luks.fido2Support path is scripted-initrd-only and refuses to
  # eval here).
  #
  # YubiKey enrollment (metal, once per key — with the key plugged
  # in; ADDS a slot, touches nothing else — passphrase/recovery/TPM
  # slots all stay):
  #   sudo systemd-cryptenroll --fido2-device=auto \
  #     /dev/disk/by-partlabel/framework-root
  #   # touch the key when it blinks. A spare YubiKey = run it again
  #   # with that key plugged in = its own slot, same ceremony.
  # Non-destructive test from the booted system (no reboot needed):
  #   sudo systemd-cryptsetup attach fido2test \
  #     /dev/disk/by-partlabel/framework-root - fido2-device=auto
  #   sudo systemd-cryptsetup detach fido2test
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-partlabel/framework-root";
    allowDiscards = true;
    crypttabExtraOpts = [ "tpm2-device=auto" "fido2-device=auto" ];
  };

  # The btrfs inside the container mounts three ways: its top-level
  # (subvolid 5) at /, plus the `home` and `nix` subvolumes. Every
  # btrfs mount carries the same two options — mount options are
  # PER-MOUNT, subvolume mounts do not inherit them from / — and the
  # same list is stated in nixos/_hardware.nix and _disko.nix so the
  # fleet's btrfs posture is one fact kept identical three places:
  #   - compress=zstd:3 — heuristic (NOT compress-force) compression,
  #     level 3 being the kernel default. The explicit level is not
  #     decoration: this kernel echoes `compress=zstd:3` back in
  #     /proc/mounts for ANY input spelling (plain compress=zstd
  #     normalizes to :3), and the disko test compares the booted
  #     layout's live options against this list option-for-option —
  #     the plain spelling failed exactly that assert (2026-09,
  #     disko:framework run). /nix is most of the bytes
  #     on this disk and generations churn it constantly, so the
  #     store re-compresses itself through plain use; the heuristic
  #     also skips the store's already-compressed payloads instead
  #     of burning CPU on them. New writes only — existing extents
  #     stay uncompressed until rewritten, and a forced defrag to
  #     hurry that would un-share every extent the existing snapper
  #     snapshots hold (usage balloons), so: let churn do it.
  #   - noatime — kills atime CoW churn: a plain read otherwise
  #     dirties the page, and thereby every hourly snapshot sharing
  #     that extent (relatime, the kernel default, still writes once
  #     a day). Mount options apply at mount time — the reboot after
  #     `switch` is what activates them; switch never remounts /.
  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "compress=zstd:3" "noatime" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress=zstd:3" "noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=home" "compress=zstd:3" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/framework-ESP";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # No swap partition since the LUKS rework (the 67G installer
  # artifact is gone — _disko.nix's header covers why zramSwap +
  # earlyoom + s2idle make it dead weight, and why plaintext swap
  # would have undone the encryption).
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
